# Generated by Django 5.1.1 on 2024-09-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='state_category',
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='substate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('state_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.statecategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.substate'),
        ),
    ]
