# Generated by Django 5.1.1 on 2024-09-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_state_category_alter_producttype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecategory',
            name='description',
            field=models.TextField(default='1'),
        ),
    ]
