# Generated by Django 5.1.1 on 2024-09-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_profile_sellerprofile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
