# Generated by Django 5.1.1 on 2024-10-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_seller_alter_product_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.substate'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
